create table if not exists public."SurveyResponse" (
  id integer generated by default as identity primary key,
  "firstName" varchar(100) not null,
  "lastName" varchar(100) not null,
  email varchar(255) not null unique,
  "contactNumber" varchar(20) not null,
  "dateOfBirth" date not null,
  foods varchar(255) not null,
  "ratingMovies" smallint not null check ("ratingMovies" between 1 and 5),
  "ratingRadio" smallint not null check ("ratingRadio" between 1 and 5),
  "ratingEatOut" smallint not null check ("ratingEatOut" between 1 and 5),
  "ratingTV" smallint not null check ("ratingTV" between 1 and 5),
  "submittedAt" timestamp without time zone not null default now()
);

create index if not exists "idx_survey_email"
  on public."SurveyResponse" (email);

create index if not exists "idx_survey_dob"
  on public."SurveyResponse" ("dateOfBirth");

create index if not exists "idx_survey_submitted"
  on public."SurveyResponse" ("submittedAt");

create index if not exists "idx_survey_submitted_id"
  on public."SurveyResponse" ("submittedAt", id);

alter table public."SurveyResponse" enable row level security;

drop policy if exists "Allow anonymous survey inserts"
  on public."SurveyResponse";

create policy "Allow anonymous survey inserts"
  on public."SurveyResponse"
  for insert
  to anon
  with check (true);

drop policy if exists "Allow anonymous aggregate reads"
  on public."SurveyResponse";

create or replace function public.get_survey_results()
returns table (
  total_count integer,
  avg_age numeric,
  min_age integer,
  max_age integer,
  pizza_percentage numeric,
  pasta_percentage numeric,
  pap_and_wors_percentage numeric,
  movies_average numeric,
  radio_average numeric,
  eat_out_average numeric,
  tv_average numeric
)
language sql
security definer
set search_path = public
as $$
  with totals as (
    select count(*)::integer as total_count
    from public."SurveyResponse"
  ),
  ages as (
    select extract(year from age(current_date, "dateOfBirth"))::integer as age
    from public."SurveyResponse"
  ),
  food_entries as (
    select lower(trim(food)) as food
    from public."SurveyResponse"
    cross join lateral unnest(string_to_array(foods, ',')) as food
  ),
  food_counts as (
    select
      count(*) filter (where food = 'pizza')::integer as pizza_count,
      count(*) filter (where food = 'pasta')::integer as pasta_count,
      count(*) filter (
        where food in ('pap and wors', 'papandwors')
      )::integer as pap_and_wors_count
    from food_entries
  ),
  rating_averages as (
    select
      round(avg("ratingMovies")::numeric, 1) as movies_average,
      round(avg("ratingRadio")::numeric, 1) as radio_average,
      round(avg("ratingEatOut")::numeric, 1) as eat_out_average,
      round(avg("ratingTV")::numeric, 1) as tv_average
    from public."SurveyResponse"
  )
  select
    totals.total_count,
    round(avg(ages.age)::numeric, 1) as avg_age,
    min(ages.age)::integer as min_age,
    max(ages.age)::integer as max_age,
    case
      when totals.total_count = 0 then null
      else round((food_counts.pizza_count::numeric / totals.total_count) * 100, 1)
    end as pizza_percentage,
    case
      when totals.total_count = 0 then null
      else round((food_counts.pasta_count::numeric / totals.total_count) * 100, 1)
    end as pasta_percentage,
    case
      when totals.total_count = 0 then null
      else round((food_counts.pap_and_wors_count::numeric / totals.total_count) * 100, 1)
    end as pap_and_wors_percentage,
    rating_averages.movies_average,
    rating_averages.radio_average,
    rating_averages.eat_out_average,
    rating_averages.tv_average
  from totals
  cross join food_counts
  cross join rating_averages
  left join ages on true
  group by
    totals.total_count,
    food_counts.pizza_count,
    food_counts.pasta_count,
    food_counts.pap_and_wors_count,
    rating_averages.movies_average,
    rating_averages.radio_average,
    rating_averages.eat_out_average,
    rating_averages.tv_average;
$$;

grant execute on function public.get_survey_results() to anon;
grant execute on function public.get_survey_results() to authenticated;
